name: C/C++ CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prerequisites
      run: |
        sudo apt-get install -y graphviz imagemagick optipng
        sudo wget -P /usr/local/share/fonts https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-UltraLight.ttf
        sudo wget -P /usr/local/share/fonts https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Light.ttf
        sudo fc-cache -fv
    - name: make checks
      run: make checks
    - name: make release
      run: make -j$(getconf _NPROCESSORS_ONLN) release
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: publishers.png
